### ISSUE TITLE
Fix user preferences page 

### ISSUE THREAD

**Issue by mmenestr** [RedHatInsights/user-preferences-frontend#39]
@fhlavac Just noticed that in your last PR, you merged the "Your information" section, and the "Email subscriptions" section.
Could you please separate them again so they each live on their own card?

Also, could you remove this extra padding here: 
![image](https://user-images.githubusercontent.com/51165119/88324190-54cb0f80-ccf1-11ea-9318-f2043136a1de.png)

**Comment by fhlavac** [comment]
Merging the sections is not caused by my last PR, it probably happened with the PF upgrade. @karelhala said he would look into it. I'm gonna remove the padding, thanks for reporting @mmenestr
